blank_issues_enabled: false
contact_links:
  - name: Вопросы и обсуждения
    url: https://github.com/dev-leva1/discord-bot/discussions
    about: Пожалуйста, используйте Discussions для вопросов и идей
